# C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP17=y

# TFLM & Ethos-U NPU
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_ETHOS_U=y

# Memory Configurations
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=8192

# Float & Logging
CONFIG_LOG=y
CONFIG_REQUIRES_FLOAT_PRINTF=y
